networks:
  interal:
    driver: bridge

volumes:
  postgres-data:

services:
  go-server:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: go-subscription-server

    volumes:
      - ./:/var/www/go

    ports:
      - 8080:8080

    networks:
      - interal

  postgres-db:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped

    environment:
      - POSTGRES_USER=postgres_admin
      - POSTGRES_PASSWORD=q1w2e3r4t5y6u7i8o9p0
      - POSTGRES_DB=postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - interal


  pg-admin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: q1w2e3r4t5y6u7i8o9p0
      PGADMIN_LISTEN_PORT: 8088
    
    ports:
      - 8088:8088
    
    depends_on:
      - postgres-db

    networks:
      - interal